image: gitpod/workspace-full-vnc
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - before: |
      sudo apt-get install -y ffmpeg
      echo y | pyenv install 3.10
      pyenv global 3.10
    init: pip3 install -r requirements.txt
    command: python3 example_of_deltas.py